#!/usr/bin/bash

	
version="v0.2"

if [ ! -z $1 ]
then
	if [ $1 = "tmp" ]
	then
		if [ ! -z $2 ]
		then
			echo "creating tmp folder"
			curl -LO $2
			cd /tmp/
			rm -vrf idur-$2-tmp
			mkdir -p idur-$2-tmp
			cd idur-$2-tmp
		else
			echo "need a name"
		fi
	elif [ $1 = "-v" ]
	then
		echo $version
	elif [ $1 = "--version" ]
	then
		echo $version
	elif [ $1 = "rm-tmp" ]
	then
		if [ ! -z $2 ]
		then
			echo "removing tmp folder"
			cd /tmp/
			rm -vrf idur-$2-tmp
		else
			echo "need a name"
		fi
		
	elif [ $1 = "download" ]
	then
		if [ ! -z $2 ]
		then
			echo "downloading $2"
			curl -LO $2
		else
			echo "need a link"
		fi
	elif [ $1 = "read" ]
	then
		if [ ! -z $2 ]
		then
			curl -L $2
		else
			echo "need a link"
		fi
	elif [ $1 = "rm" ]
	then
		if [ ! -z $2 ]
		then
			rm -vrf $2
		else
			echo "need files"
		fi
	else
		echo "idur-pkg
Use:
	idur-pkg <option> <optional>
Options:
	tmp                   create /tmp/idur-pkg-tmp folder
	rm                    remove /tmp/idur-pkg-tmp folder
	download <link>       download the link
	read     <link>       read the link
	rm       <file>       remove the file"
	fi
else
	echo "idur-pkg
Use:
	idur-pkg <option> <optional>
Options:
	tmp                   create /tmp/idur-pkg-tmp folder
	rm                    remove /tmp/idur-pkg-tmp folder
	download <link>       download the link
	read     <link>       read the link
	rm       <file>       remove the file"
fi

