#!/usr/bin/bash

	
version="v0.5"

all=" $2 $3 $4 $5 $6 $7 $8 $9 "
first=$1
second=$2

if [ -z $1 ]
then
	first=" "
	second=" "
fi

if [[ $first = "tmp" ]]
then
	if [[ ! $second = "" ]]
	then
		/usr/bin/echo "creating tmp folder"
		cd /tmp/
		/usr/bin/rm -vrf idur-$second-tmp
		/usr/bin/mkdir -p idur-$second-tmp
		cd idur-$second-tmp
	else
		/usr/bin/echo "need a name"
	fi
elif [[ $first = "dir-tmp" ]]
then
	if [[ ! $second = "" ]]
	then
		/usr/bin/echo "idur-$second-tmp"
	else
		/usr/bin/echo "need a name"
	fi
elif [[ $first = "dp" ]]
then
	if [[ ! $second = "" ]]
	then
		/usr/bin/echo "/tmp/idur-$second-tmp/"
	else
		/usr/bin/echo "need a name"
	fi
elif [[ $first = "-v" ]] || [[ $first = "--version" ]]
then
	/usr/bin/echo $version
elif [[ $first = "rm-tmp" ]]
then
	if [[ ! $second = "" ]]
	then
		/usr/bin/echo "removing tmp folder"
		cd /tmp/
		/usr/bin/rm -vrf idur-$second-tmp
	else
		/usr/bin/echo "need a name"
	fi
	
elif [[ $first = "download" ]]
then
	if [[ ! $second = "" ]]
	then
		/usr/bin/echo "downloading $second"
		/usr/bin/curl -LO $second
	else
		/usr/bin/echo "need a link"
	fi
elif [[ $first = "read" ]]
then
	if [[ ! $second = "" ]]
	then
		/usr/bin/curl -L $second
	else
		echo "need a link"
	fi
elif [[ $first = "rm" ]]
then
	if [[ ! $second = "" ]]
	then
		/usr/bin/rm -vrf $all
	else
		echo "need files"
	fi
elif [[ $first = "uncompress" ]]
then
	if [[ ! $second = "" ]]
	then
		/usr/bin/dunpress $all
	else
		/usr/bin/echo "need files"
	fi
elif [[ $first = "exec" ]]
then
	if [[ ! $second = "" ]]
	then
		/usr/bin/chmod a+x -R $second
	else
		/usr/bin/echo "need files"
	fi
elif [[ $first = "mod" ]]
then
	if [[ ! $second = "" ]]
	then
		/usr/bin/chmod a+rw -R $second
	else
		/usr/bin/echo "need files"
	fi
else
	/usr/bin/echo "idur-pkg
Use:
	idur-pkg <option> <optional>
Options:
	tmp             <name>       create /tmp/idur-pkg-tmp folder
	rm-tmp          <name>       remove /tmp/idur-pkg-tmp folder
	dp              <name>       print /tmp/idur-pkg-tmp folder
	download        <link>       download the link
	read            <link>       read the link
	rm              <file>       remove the file
	uncompress      <file>       uncompress files
	exec            <file>       make executable
	mod             <file>       all can write the files
	                             (useful to programs that
	                             save data in its folder)"
fi

